// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLx0hX_4hSepd07htKkNrztIOlXgkHS0',
    appId: '1:607010515271:web:ae68a9c6ca659d57c6c462',
    messagingSenderId: '607010515271',
    projectId: 'blood-bank-finder-46bc3',
    authDomain: 'blood-bank-finder-46bc3.firebaseapp.com',
    storageBucket: 'blood-bank-finder-46bc3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrk2-5oEMt29LGA7HGGPdlYspOczeipks',
    appId: '1:607010515271:android:364b5ccb307ddb82c6c462',
    messagingSenderId: '607010515271',
    projectId: 'blood-bank-finder-46bc3',
    storageBucket: 'blood-bank-finder-46bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR21s4qgylRj9jb-QKu53weskamRoA1js',
    appId: '1:607010515271:ios:03982ebfa2ca60b5c6c462',
    messagingSenderId: '607010515271',
    projectId: 'blood-bank-finder-46bc3',
    storageBucket: 'blood-bank-finder-46bc3.firebasestorage.app',
    iosBundleId: 'com.example.bloodBankFinder',
  );
}
