"""
FILE: models.py (Pydantic Models)

DESCRIPTION:
This file defines the data structure "Blueprints" for the entire backend. 
It uses Pydantic to ensure that any data coming from the Flutter app is 
valid (e.g., email is a string, units is a number) before the backend 
even tries to process it.

DATA FLOW OVERVIEW:
1. RECEIVES DATA FROM: 
   - The Flutter Frontend (via JSON in the body of HTTP requests).
2. PROCESSING:
   - Validation: Pydantic automatically checks the types and presence of fields.
   - Serialization: Converts JSON objects into Python-friendly objects.
3. SENDS DATA TO:
   - 'FirestoreService': The routers pass these validated models to the 
     service layer to be saved to the database.
4. OUTPUTS:
   - 'Response' models: Define exactly what JSON fields the Flutter app will 
     see in return.

COMPONENTS:
- User Models: For profile management (uid, role, location).
- Hospital Models: For directory entries (coordinates, contact info).
- BloodRequest Models: For the core 'Request' and 'Donate' operations.
- Inventory Models: For tracking stock levels.
- Notification Models: For internal alerts.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

# --- USER MODELS ---
class UserBase(BaseModel):
    """The foundation of a User record, shared by Create and Response models."""
    uid: str
    email: str
    role: str = "user" # Default role is 'user' until promoted by admin.
    firstName: str
    lastName: str
    fatherName: str
    mobile: str
    gender: str
    bloodGroup: str
    islandGroup: str
    region: str
    city: str
    barangay: str
    address: str
    hospitalId: Optional[str] = None # Only for Hospital Admins.
    isBanned: bool = False
    createdAt: datetime = Field(default_factory=datetime.now)

class UserCreate(UserBase):
    """Used when the Flutter app sends a new user profile to be saved."""
    pass

class UserResponse(UserBase):
    """The JSON structure returned to the app when fetching user info."""
    pass

# --- HOSPITAL MODELS ---
class HospitalBase(BaseModel):
    """The foundation of a Hospital record."""
    name: str
    email: str
    islandGroup: str
    region: str
    city: str
    barangay: str
    address: str
    contactNumber: str
    latitude: float
    longitude: float
    availableBloodTypes: List[str]
    isActive: bool = True
    createdAt: datetime = Field(default_factory=datetime.now)

class HospitalCreate(HospitalBase):
    """Used for registering a new hospital."""
    pass

class HospitalResponse(HospitalBase):
    """Includes the unique 'id' generated by Firestore."""
    id: str

# --- BLOOD REQUEST MODELS ---
class BloodRequestBase(BaseModel):
    """Represents a transaction of blood (Requesting or Donating)."""
    userId: str
    userName: str
    type: str # 'Request' or 'Donate'
    bloodType: str
    status: str = "pending" # Standard lifecycle: pending -> on progress -> completed/rejected.
    hospitalId: str
    hospitalName: str
    contactNumber: str
    quantity: float
    adminMessage: Optional[str] = None # Added to store feedback from Hospital Admins.
    createdAt: datetime = Field(default_factory=datetime.now)

class BloodRequestCreate(BloodRequestBase):
    """Used when a user fills out the Request or Donate form."""
    pass

class BloodRequestResponse(BloodRequestBase):
    """Unique transaction record with ID."""
    id: str

# --- INVENTORY MODELS ---
class InventoryBase(BaseModel):
    """Tracking stock levels for a specific blood type in a specific hospital."""
    blood_type: str
    units: float
    last_updated: datetime = Field(default_factory=datetime.now)

class InventoryCreate(InventoryBase):
    pass

class InventoryResponse(InventoryBase):
    pass

# --- NOTIFICATION MODELS ---
class NotificationBase(BaseModel):
    """In-app alerts sent to users regarding their requests."""
    userId: str
    message: str
    isRead: bool = False
    createdAt: datetime = Field(default_factory=datetime.now)
    type: Optional[str] = None
    title: Optional[str] = None
    body: Optional[str] = None

class NotificationCreate(NotificationBase):
    pass

class NotificationResponse(NotificationBase):
    """Unique notification record with ID."""
    id: str
